### PR TITLE
fix: Correct type definition for waitForAllMessagesAcknowledged

### PR DESCRIPTION
**Pull request by valentin-nemcev**
Type definition doesn't match documentation and code, seems like it was a typo

### CODE REVIEW

**Review by timfish — APPROVED** [review]

**Comment by timfish** [comment]
Thanks!

**Review by charsleysa — APPROVED** [review]
LGTM

**Comment by charsleysa** [comment]
@timfish is this PR able to be merged and released?

**Comment by timfish** [comment]
> @timfish is this PR able to be merged and released?

Yep, it just needs another review so I've just requested some!

**Review by dygabo — APPROVED** [review]

**Comment by timfish** [comment]
This was released in v1.11.3 which will be on npm shortly!

**Pull request merged**
